language: node_js

node_js:
  - '10'

before_script:
  - npm install 

script:
  - npm run build

after_success:
  - cd src
  - git init
  - git config user.email "travis@example.com"
  - git config user.name "Travis CI"
  - git remote add origin https://${GH_AUTH}@github.com/talenfisher/fix3p.git
  - git fetch
  - git stash && git checkout gh-pages && git stash pop
  - git add .
  - git commit -m "Building pages [jobid:$TRAVIS_BUILD_NUMBER]"
  - git push --set-upstream origin gh-pages --quiet

branches:
  only:
    - master 