language: node_js

node_js:
  - '10'

before_script:
  - npm install 
  - cd src && git init
  - git config user.email "travis@example.com"
  - git config user.name "Travis CI"
  - git remote add origin https://${GH_AUTH}@github.com/talenfisher/fix3p.git
  - git fetch
  - git reset origin/gh-pages && git checkout gh-pages
  - cd ../

script:
  - npm run build

after_success:
  - cd src
  - sed -i "s/{{version}}/$TRAVIS_BUILD_NUMBER/" index.html
  - git add .
  - git commit -m "Pages build $TRAVIS_BUILD_NUMBER"
  - git push --quiet

branches:
  only:
    - master 