language: node_js

node_js:
  - '10'

before_script:
  - npm install 
  - cd src && git init
  - git config user.email "travis@example.com"
  - git config user.name "Travis CI"
  - git remote add origin https://${GH_AUTH}@github.com/talenfisher/fix3p.git
  - git fetch
  - git reset origin/gh-pages && git checkout gh-pages
  - cd ../

script:
  - npm run build

deploy:
  - provider: script
    script: bash bin/deploy
    skip_cleanup: true
    on:
      branch: master

  - provider: releases
    api_key: $GH_AUTH
    skip_cleanup: true
    file: "extension.zip"
    on:
      tags: true